  Skip to content
    Search or jump to…

    Pull requests
    Issues
    Marketplace
    Explore

    @dashixiong-11
    jirengu-inc
    /
    fui-city
    2
    22
    Code
    Issues
    Pull requests
    4
    Actions
    Projects
    Wiki
    Security
    Insights
    fui-city/.circleci/config.yml
    @FrankFang
    FrankFang add ci config
    Latest commit d446380 on 24 Mar 2019
    History
    1 contributor
    75 lines (71 sloc)  1.53 KB

  #https://github.com/revolunet/create-react-app-circleci/blob/master/.circleci/config.yml
  defaults: &defaults
    docker:
      - image: circleci/node:8

  version: 2
  jobs:
    prepare:
      <<: *defaults
      steps:
        - checkout
        - restore_cache:
            keys:
              - v2-dependencies-{{ checksum "package.json" }}
        - run: yarn install
        - save_cache:
            paths:
              - node_modules
            key: v2-dependencies-{{ checksum "package.json" }}
        - persist_to_workspace:
            root: .
            paths:
              - node_modules
    build:
      <<: *defaults
      steps:
        - checkout
        - attach_workspace:
            at: .
        - run: yarn build
        - persist_to_workspace:
            root: .
            paths:
              - dist
              - package.json
              - LICENSE
              - README.md
    test:
      <<: *defaults
      steps:
        - checkout
        - attach_workspace:
            at: .
        - run: yarn ci
        - store_test_results:
            path: test-results
    publish:
      <<: *defaults
      steps:
        - attach_workspace:
            at: .
        - run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        - run: npm publish



  workflows:
    version: 2
    build_accept_deploy:
      jobs:
        - prepare
        - build:
            requires:
              - test
        - test:
            requires:
              - prepare
        - publish:
            requires:
              - build
            filters:
              tags:
                only: /^v[0-9]+(\.[0-9]+)*/
              branches:
                ignore: /.*/
